apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: TrainingPortal
metadata:
  name: onyx-playgrounds
spec:
  portal:
    title: Onyx Playgrounds
    logo: https://www.jpmorgan.com/onyx/images/logo.svg
    registration:
      type: anonymous
    updates:
      workshop: true
    password: onyx-demo
  workshops:
  - name: miner
    capacity: 10
    reserved: 3
    expires: 24h
    orphaned: 1h
