apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: Workshop
metadata:
  name: sample-learning
spec:
  title: Markdown Sample
  description: A sample workshop using Markdown
  vendor: learningcenter.tanzu.vmware.com
  difficulty: beginner
  duration: 15m
  url: https://github.com/nmahajan-jpmc/sample_learning
  content:
    #image: quay.io/eduk8s/lab-markdown-sample:master
    files: github.com/nmahajan-jpmc/sample_learning
  session:
    ingresses:
    - name: quorum
      port: 25000
    namespaces:
      budget: small
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
    dashboards:
    - name: quorum
      url: "$(ingress_protocol)://$(session_namespace)-quorum.$(ingress_domain)/"
