apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: Workshop
metadata:
  name: miner
spec:
  title: The Miner
  description: A playground digging deeper into a pre-installed quorum setup. This will let you create/compile and deploy smart-contracts and dApps using Truffle
  vendor: learningcenter.tanzu.vmware.com
  difficulty: beginner
  duration: 1 day
  url: https://github.com/nmahajan-jpmc/sample_learning
  content:
    #image: quay.io/eduk8s/lab-markdown-sample:master
    files: github.com/nmahajan-jpmc/sample_learning
  session:
    resources:
      memory: 4Gi
    ingresses:
    - name: quorum
      port: 25000
    namespaces:
      budget: small
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
    dashboards:
    - name: quorum
      url: "$(ingress_protocol)://$(session_namespace)-quorum.$(ingress_domain)/"
